CODECOV_TOKEN: 911c9d3c-a567-4ce0-a32c-9a715830f02e
coverage:
  parsers:
    javascript:
      enable_partials: no
fixes:
  - "coverage/-*::coverage/lcov-report"
services:
   ci_providers:
     - https://travis-ci.org/  # domain name only