language: node_js
node_js:
  - 9
  - 6
cache: false
addons:
- postgresql: "9.4"
services:
- postgresql
global:
  - export NODE_ENV=test
before_script:
- psql -c "CREATE DATABASE \"boots_test\";" -U postgres
- npm install
install:
  - npm install -g codecov
script:
  - npm run test
after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < cat ./coverage/lcov.info
  - CODECOV_TOKEN=$CODECOV_TOKEN
  - npm run coverage
  - codecov
  
