language: node_js
node_js:
  - 9
  - 6
env:
  - SECRET_KEY=#(@#GYzU#EWERGFXTSWEW(@#YW($EW(
  global:
    - export NODE_ENV=test
  script:
  - npm install
  - npm run test
  - npm run coverage

  after_success: 'npm run coveralls'
