language: node_js
node_js:
  - 9
  - 6
cache:
  directories:
  - node_modules
addons:
- postgresql: "9.4"
services:
- postgresql
global:
  - export NODE_ENV=test
before_script:
- psql -c "CREATE DATABASE \"boots_test\";" -U postgres
- npm install
script:
  - npm run test
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run coverage
