language: node_js
node_js:
  - 9
  - 6
env:
  global:
    - export NODE_ENV=test
  script:
  - travis_wait npm test
  - travis_wait npm run coverage
  - travis_wait npm install

  after_success: 'npm run coveralls'
