language: node_js
node_js:
  - 9
  - 6
cache: false
addons:
- postgresql: "9.4"
env:
  - CODECOV_TOKEN=911c9d3c-a567-4ce0-a32c-9a715830f02e
services:
- postgresql
global:
  - export NODE_ENV=test
before_script:
- psql -c "CREATE DATABASE \"boots_test\";" -U postgres
- npm install
install:
  - npm install -g codecov
script:
  - npm run test
  - codecov
after_success:
  - codeclimate-test-reporter < cat ./coverage/lcov.info
  - npm run coverage
