export const ADD_USER = 'ADD_USER';
export const SET_USER = 'SET_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const ADD_CENTER_SUCCESS = 'ADD_CENTER_SUCCESS';
export const ADD_CENTER_FAlLURE = 'ADD_CENTER_FAlLURE';
export const ADD_CENTER_REQUEST = 'ADD_CENTER_REQUEST';
export const FETCH_CENTERS = 'FETCH_CENTERS';
export const FETCH_CENTER_DETAIL = 'FETCH_CENTER_DETAIL';
export const FETCH_RELATED_CENTERS = 'FETCH_RELATED_CENTERS';
export const EDIT_CENTER = 'EDIT_CENTER';
export const REMOVE_CENTER = 'REMOVE_CENTER';

export const FETCH_EVENTS = 'FETCH_EVENTS';
export const ADD_EVENT = 'ADD_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
export const EDIT_EVENT_REQUEST = 'EDIT_EVENT_REQUEST';
export const REMOVE_EVENT = 'REMOVE_EVENT';
