export const ADD_USER = 'ADD_USER';
export const SET_USER = 'SET_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const ADD_CENTER_SUCCESS = 'ADD_CENTER_SUCCESS';
export const ADD_CENTER_FAlLURE = 'ADD_CENTER_FAlLURE';
export const ADD_CENTER_REQUEST = 'ADD_CENTER_REQUEST';
export const FETCH_CENTERS = 'FETCH_CENTERS';
export const FETCH_CENTER_DETAIL = 'FETCH_CENTER_DETAIL';
export const FETCH_RELATED_CENTER = 'FETCH_RELATED_CENTER';

export const FETCH_EVENTS = 'FETCH_EVENTS';
export const ADD_EVENT = 'ADD_CENTER';